name: Build Android Application

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Android/**'
  pull_request:
    paths:
      - 'Android/**'
      
  workflow_dispatch:

jobs:
  build-android-app:
    name: Build Android App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        working-directory: ./Android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: Android/app/build/outputs/apk/debug/app-debug.apk
