name: Combined CI Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # Job 1: Build the Android Application
  build-android-app:
    name: Build Android App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Android App
        id: build
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          gradle_task: assembleDebug
          project_path: LinuxIsoBuilderAndroid/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: ${{ steps.build.outputs.apk_path }}

  # Job 2: Test the Ruby Project
  test-ruby:
    name: Build and Test Ruby
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true 

      - name: Run tests
        run: bundle exec rake
