name: Build Full Arch Linux ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Pacman and Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git base-devel archiso wget go

      - name: Configure Git
        run: |
          git config --global user.name "KrzysTheTech"
          git config --global user.email "krzysztofdemirkuzniak@gmail.com"

      - name: Create archiso Profile
        run: |
          cp -r /usr/share/archiso/configs/releng/ archlive

      - name: Build AUR Helper and Create Local Repo
        run: |
          mkdir -p /yay_repo
          git clone https://aur.archlinux.org/yay.git
          cd yay
          chown -R nobody:nobody .
          sudo -u nobody GOCACHE="$(pwd)/.cache" makepkg -s --noconfirm
          repo-add /yay_repo/yay.db.tar.gz *.pkg.tar.zst
          cd ..
          rm -rf yay

      - name: Configure Pacman to use Local Repo
        run: |
          cat <<EOF > archlive/pacman.conf
          [options]
          Architecture = auto
          CheckSpace
          SigLevel = Never
          ParallelDownloads = 10

          [yay]
          SigLevel = Optional TrustAll
          Server = file:///yay_repo

          [core-testing]
          Include = /etc/pacman.d/mirrorlist
          [core]
          Include = /etc/pacman.d/mirrorlist
          [extra-testing]
          Include = /etc/pacman.d/mirrorlist
          [extra]
          Include = /etc/pacman.d/mirrorlist
          [kde-unstable]
          Include = /etc/pacman.d/mirrorlist
          [gnome-unstable]
          Include = /etc/pacman.d/mirrorlist
          [multilib-testing]
          Include = /etc/pacman.d/mirrorlist
          [multilib]
          Include = /etc/pacman.d/mirrorlist
          [testing]
          Include = /etc/pacman.d/mirrorlist
          EOF

      - name: Define Extensive Package List (Full Installation)
        run: |
          cat <<EOF > archlive/packages.x86_64
          # --- BASE SYSTEM & BOOTLOADER (NOW GRUB) ---
          base base-devel linux linux-firmware
          grub mtools syslinux edk2-shell memtest86+ memtest86+-efi
          # --- AUR HELPER ---
          yay
          # --- INSTALLER & LIVE ENVIRONMENT ---
          archiso calamares fastfetch htop wget curl unzip p7zip networkmanager
          xorg-server xorg-xinit openbox tint2
          # --- DESKTOP ENVIRONMENTS (ALL INCLUDED) ---
          plasma-meta kde-applications-meta
          gnome gnome-extra
          xfce4 xfce4-goodies
          cinnamon
          mate mate-extra
          budgie-desktop budgie-extras
          deepin deepin-extra
          # --- WINDOW MANAGERS & WAYLAND (ALL INCLUDED) ---
          i3-wm i3status dmenu
          awesome
          qtile
          bspwm sxhkd
          sway waybar wofi
          hyprland xdg-desktop-portal-hyprland
          wayfire
          # --- WEB BROWSERS & NETWORKING ---
          firefox chromium brave-browser
          thunderbird
          filezilla
          # --- OFFICE & PRODUCTIVITY ---
          libreoffice-fresh onlyoffice-desktopeditors
          gimp inkscape scribus zotero
          # --- DEVELOPMENT ---
          git gcc gdb make cmake python python-pip nodejs npm go rust neovim code qtcreator docker podman
          # --- VIRTUALIZATION ---
          qemu-full virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat
          virtualbox virtualbox-guest-iso
          # --- MULTIMEDIA & GRAPHICS ---
          vlc mpv ffmpeg kdenlive shotcut openshot blender obs-studio audacity lmms krita mypaint darktable rawtherapee shotwell gwenview spotify-launcher
          # --- GAMING ---
          steam lutris wine gamemode
          0ad the-battle-for-wesnoth freeciv flightgear openttd endless-sky
          xonotic assaultcube sauerbraten teeworlds supertuxkart hedgewars extremetuxracer
          supertux pingus frozen-bubble neverball
          minetest flare-engine valyria-tear
          # --- UTILITIES ---
          gparted bleachbit timeshift stacer veracrypt keepassxc qbittorrent conky
          # --- FONTS ---
          noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-dejavu ttf-liberation
          EOF

      - name: Configure Calamares for GRUB Installation
        run: |
          mkdir -p archlive/airootfs/etc/calamares/modules
          
          # Calamares settings now include the 'bootloader' module
          cat <<EOF > archlive/airootfs/etc/calamares/settings.conf
          modules-load:
            - welcome
            - keyboard
            - partition
            - unpackfs
            - users
            - bootloader
            - summary
            - finished
          branding: archlinux
          prompt-install: false
          -id: preserve-user-home-on-reinstall
          EOF
          
          # Configuration for the bootloader module to install GRUB
          cat <<EOF > archlive/airootfs/etc/calamares/modules/bootloader.conf
          ---
          bootloader: "grub"
          
          grub_cfg: "/boot/grub/grub.cfg"
          
          efi_directory: "/boot"
          
          grub_install_args:
              - "--target=x86_64-efi"
              - "--efi-directory=/boot"
              - "--bootloader-id=arch"
              - "--recheck"
          EOF

          # Previous Calamares configurations
          mkdir -p archlive/airootfs/etc/calamares/branding/archlinux
          cat <<EOF > archlive/airootfs/etc/calamares/branding/archlinux/branding.desc
          componentName: archlinux
          welcomeStyle: "true"
          welcomeText: |
            <h2>Welcome to the Arch Linux Full installer.</h2>
            <p>This installer will copy the complete live environment, including all applications and desktop environments, to your computer.</p>
            <p><b>WARNING:</b> This build uses testing repositories and is intended for experienced users who are comfortable with potential system instability.</p>
          productName: Arch Linux
          productVersion: Rolling (Full)
          productUrl: "https://archlinux.org"
          shortName: Arch Linux
          productLogo: "/usr/share/pixmaps/archlinux-logo.svg"
          EOF
          cat <<EOF > archlive/airootfs/etc/calamares/modules/unpackfs.conf
          ---
          unpack:
              - source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
                sourcefs: "squashfs"
                destination: ""
          EOF
          cat <<EOF > archlive/airootfs/etc/calamares/modules/partition.conf
          ---
          efiSystemPartition: "/boot"
          efiSystemPartitionSize: 512M
          create-swap: true
          swap-size: 2048M
          default-filesystem: "ext4"
          EOF
          # The finished module no longer needs a custom script
          cat <<EOF > archlive/airootfs/etc/calamares/modules/finished.conf
          ---
          reboot-now: true
          EOF


      - name: Configure Calamares Autostart
        run: |
          mkdir -p archlive/airootfs/etc/systemd/system/getty@tty1.service.d/
          cat <<EOF > archlive/airootfs/etc/systemd/system/getty@tty1.service.d/autologin.conf
          [Service]
          ExecStart=
          ExecStart=-/usr/bin/agetty --autologin root --noclear %I \$TERM
          EOF
          cat <<EOF > archlive/airootfs/root/.xinitrc
          #!/bin/sh
          openbox &
          tint2 &
          calamares --fullscreen
          EOF
          chmod +x archlive/airootfs/root/.xinitrc
          cat <<EOF > archlive/airootfs/root/.bash_profile
          [[ -z \$DISPLAY && \$XDG_VTNR -eq 1 ]] && startx
          EOF

      - name: Configure ISO Profile
        run: |
          # ISO Profile configuration with updated boot modes
          cat <<EOF > archlive/profile.conf
          iso_name="archlinux-full"
          iso_label="ARCH_FULL_$(date +%Y%m)"
          iso_publisher="KrzysTheTech <krzysztofdemirkuzniak@gmail.com>"
          iso_application="Arch Linux Full Installer"
          iso_version="$(date +%Y.%m.%d)"
          install_dir="arch"
          buildmodes=('iso')
          bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito'
                     'uefi-shell' 'uefi-ia32.grub.esp' 'uefi-x64.grub.esp')
          airootfs_image_tool_options=('-comp' 'xz' '-b' '1M')
          file_permissions=(
            ["/etc/shadow"]="0:0:400"
            ["/root"]="0:0:750"
          )
          EOF

      - name: Build the ISO
        run: |
          mkarchiso -v -w work -o out archlive

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-full-${{ env.TIMESTAMP }_grub}-x86_64.iso
          path: out/*.iso
