name: Build All Source and Binary Packages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  APP_VERSION: "0.1.0"
  APP_RELEASE_NAME: "alpha1"

jobs:
  build-source-packages:
    name: Build Source Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'repo_source'

      - name: Generate Version String
        run: echo "VERSION_STRING=${{ env.APP_VERSION }}-${{ env.APP_RELEASE_NAME }}~$(date +%Y%m%d)-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Install Packaging Tools
        run: sudo apt-get update && sudo apt-get install -y devscripts debhelper rpm build-essential

      - name: Create Source Tarball
        run: |
          FULL_VERSION_STRING="${{ env.VERSION_STRING }}"
          UPSTREAM_VERSION="${FULL_VERSION_STRING%-*}"
          tar -cJf "linuxisobuilder_${UPSTREAM_VERSION}.orig.tar.xz" \
            --exclude=./repo_source/.git \
            --transform="s,^repo_source,linuxisobuilder-${UPSTREAM_VERSION}," \
            ./repo_source

      - name: Create Debian Source Package
        working-directory: ./repo_source
        run: |
          mkdir -p debian
          # Create control file
          echo "Source: linuxisobuilder" > debian/control
          echo "Section: utils" >> debian/control
          echo "Priority: optional" >> debian/control
          echo "Maintainer: Krzysztofdemirkuzniak <krzysztofdemirkuzniak@gmail.com>" >> debian/control
          echo "Build-Depends: debhelper-compat (= 13), build-essential" >> debian/control
          echo "" >> debian/control
          echo "Package: linuxisobuilder-cli" >> debian/control
          echo "Architecture: any" >> debian/control
          echo "Description: CLI to build custom Linux ISOs." >> debian/control
          # Create changelog
          echo "linuxisobuilder (${{ env.VERSION_STRING }}) unstable; urgency=medium" > debian/changelog
          echo "" >> debian/changelog
          echo "  * New release." >> debian/changelog
          echo "" >> debian/changelog
          echo " -- Krzysztofdemirkuzniak <krzysztofdemirkuzniak@gmail.com>  $(date -R)" >> debian/changelog
          # Create rules file
          echo -e '#!/usr/bin/make -f\n\n%: \n\tdh $@' > debian/rules
          chmod +x debian/rules
          # Create compat file
          echo "13" > debian/compat
          # Build source package
          debuild -S -us -uc

      - name: Upload Source Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: source-packages
          path: |
            *.dsc
            *.orig.tar.xz
            *.debian.tar.xz

  build-binary-packages:
    name: Build Binary for ${{ matrix.arch }}
    needs: build-source-packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: