name: Build Debian Sid GNOME Installer (amd64)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6-hour timeout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Maximize Build Space
        run: |
          echo "Freeing up disk space..."
          sudo rm -rf /usr/share/dotnet /opt/hostedtoolcache/CodeQL /usr/local/lib/android
          echo "Disk space after cleanup:"
          df -h

      - name: Cache live-build contents
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ runner.os }}-live-build-amd64-${{ hashFiles('config/package-lists/my.list.chroot') }}
          restore-keys: |
            ${{ runner.os }}-live-build-amd64-

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y live-build debootstrap

      - name: Create live-build config
        run: |
          lb config noauto \
            --architecture amd64 \
            --distribution sid \
            --archive-areas "main contrib non-free non-free-firmware" \
            --mirror-bootstrap "http://deb.debian.org/debian/" \
            --mirror-chroot "http://deb.debian.org/debian/" \
            --debian-installer true \
            --debian-installer-gui true \
            --iso-application "Debian Sid GNOME Installer" \
            --iso-preparer "Built by GitHub Actions" \
            --iso-publisher "GitHub Actions" \
            --iso-volume "Debian Sid GNOME" \
            --memtest none \
            --cache true

      - name: Create package list
        run: |
          mkdir -p config/package-lists
          cat <<EOF > config/package-lists/my.list.chroot
          task-gnome-desktop
          firefox
          vlc
          ffmpeg
          build-essential
          kdenlive
          EOF

      - name: Build the ISO
        run: sudo lb build

      - name: Rename ISO
        run: |
          ISO_DATE=$(date +%Y%m%d)
          mv live-image-amd64.hybrid.iso "debian-sid-gnome-installer-${ISO_DATE}-amd64.iso"

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: debian-sid-gnome-installer-amd64
          path: debian-sid-gnome-installer-*-amd64.iso
