name: Build Debian Sid GNOME Installer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, riscv64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ADD THIS STEP TO FREE UP DISK SPACE
      - name: Maximize Build Space
        run: |
          echo "Freeing up disk space..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android
          echo "Disk space after cleanup:"
          df -h

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build debootstrap

      - name: Create live-build config
        run: |
          lb config noauto \
            --architecture ${{ matrix.arch }} \
            --distribution sid \
            --archive-areas "main contrib non-free non-free-firmware" \
            --mirror-bootstrap "http://deb.debian.org/debian/" \
            --mirror-chroot "http://deb.debian.org/debian/" \
            --debian-installer true \
            --debian-installer-distribution sid \
            --debian-installer-gui true \
            --iso-application "Debian Sid GNOME Installer" \
            --iso-preparer "Built by GitHub Actions" \
            --iso-publisher "GitHub Actions" \
            --iso-volume "Debian Sid GNOME" \
            --memtest none

      - name: Create package list
        run: |
          # A more realistic package list for a single-desktop ISO
          echo "task-gnome-desktop" > config/package-lists/gnome.list.chroot
          echo "firefox" >> config/package-lists/gnome.list.chroot
          echo "vlc" >> config/package-lists/gnome.list.chroot
          echo "ffmpeg" >> config/package-lists/gnome.list.chroot
          echo "build-essential" >> config/package-lists/gnome.list.chroot
          # NOTE: crossbuild-essential-* is very large. Uncomment only if absolutely needed.
          # echo "crossbuild-essential-*" >> config/package-lists/gnome.list.chroot
          echo "kdenlive" >> config/package-lists/gnome.list.chroot
          # NOTE: Removed task-kde-desktop and task-xfce-desktop for a focused build.

      - name: Build the ISO
        run: |
          sudo lb build

      - name: Rename ISO
        run: |
          ISO_NAME="debian-live-$(date +%Y%m%d)-${{ matrix.arch }}-gnome.iso"
          mv live-image-${{ matrix.arch }}.hybrid.iso "debian-sid-gnome-installer-$(date +%Y%m%d)-${{ matrix.arch }}.iso"


      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: debian-sid-gnome-installer-${{ matrix.arch }}
          path: debian-sid-gnome-installer-*-${{ matrix.arch }}.iso

